blank_issues_enabled: false
contact_links:
  - name: goat place
    url: https://discord.gg/3NMcUV5
    about: If you need help with anything, join our discord server and ask in the appropriated channel.